stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - cipipeline
  script:
    - mvn compile

test:
  stage: test
  tags:
    - cipipeline
  script:
    - mvn clean test

deploy:
  stage: deploy
  tags:
    - cipipeline
  script:
    - java -jar start.jar -Djetty.port=9999
    - mvn jetty:run-war
