stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - desktoprunner
  script:
    - mvn compile

test:
  stage: test
  tags:
    - desktoprunner
  script:
    - mvn clean test

deploy:
  stage: deploy
  tags:
    - desktoprunner
  script:
    - mvn clean deploy -P release
